// <auto-generated />
using System;
using CestaFeria.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CestaFeira.Data.Migrations
{
    [DbContext(typeof(ApsContext))]
    [Migration("20240919143351_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CestaFeira.Domain.Entityes.ProdutoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VendaEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<double>("valorUnitario")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("VendaEntityId");

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.UsuarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdUsuario");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Cel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Perfil");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Email", "Senha");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ab52682-7f30-4f2a-abfc-313261d73761"),
                            Ativo = true,
                            Bairro = "Jardim São Carlos",
                            Cel = "(35)11111111",
                            Cidade = "Alfenas",
                            Data = new DateTime(2024, 9, 19, 11, 33, 50, 783, DateTimeKind.Local).AddTicks(9402),
                            Email = "rafael@gmail.com",
                            Nome = "Administrador",
                            Numero = 555,
                            Perfil = "ADM",
                            Rua = "Juscelino Kubitschek",
                            Senha = "AAAAAAAAAAAAAAAAAAAAAA==.XX7jD2oxYNzQ1dN5QTb3mg==.8brshsL5uJMEmxK/bjA2p3rva5lNSmNTEwq5KVDM4S0=",
                            Uf = "MG",
                            cpf = "13080460812"
                        });
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.VendaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.ProdutoEntity", b =>
                {
                    b.HasOne("CestaFeira.Domain.Entityes.UsuarioEntity", "Usuario")
                        .WithMany("Produtos")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CestaFeira.Domain.Entityes.VendaEntity", null)
                        .WithMany("Produtos")
                        .HasForeignKey("VendaEntityId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.VendaEntity", b =>
                {
                    b.HasOne("CestaFeira.Domain.Entityes.UsuarioEntity", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.UsuarioEntity", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("CestaFeira.Domain.Entityes.VendaEntity", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
